linters-settings:
  goimports:
    local-prefixes: github.com/ambi/goscep

linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - goimports
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck
    - typecheck
    - unused
    - varcheck

issues:
  include:
    - EXC0004
    - EXC0005
    - EXC0006
    - EXC0007
    - EXC0009
    - EXC0010
    - EXC0011
    - EXC0012
    - EXC0013
    - EXC0014
    - EXC0015