name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2 # TODO: specify go version
      - run: go ./...
  vulns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ory/nancy-github-action@v0
